### ISSUE TITLE
Should peer-star become its own Github Org?

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/peer-star#21]
It would improve discoverability as each of the building blocks would be in a single org that has a specific focus rather than the more generic ipfs-shipyard.

**Comment by jimpick** [comment]
Seems like a good idea... perhaps the org should use the peer-base name?

**Comment by pgte** [comment]
@jimpick my thoughts also.
Perhaps we could take this opportunity to do the rename?
Also, there are some parts that we would like to extract as new packages into this org.
@daviddias was this what you had in mind?

**Comment by daviddias** [comment]
I was still thinking that `peer-star`  is the ecosystem while `peer-base` is the lib that enables apps such as `peer-pad`, `peer-flipchart`, discussify and others but I don't really have any strong feelings and I believe you will have the best intuition on how to present the whole toolkit and app blueprints to the community.

**Comment by jimpick** [comment]
I think eventually (soon?) we should have a proper landing page with some gentle introductory material about what it is, demos, docs, tutorials, etc. - similar to maybe libp2p.io or ipfs.io. It would be good to think about the whole thing holistically and come up with branding that works.

I think peer-* works as branding, but we need to think about how we explain it to others, and how also so we can explain how it connects with ipfs, libp2p, ipld, etc. New users to IPFS are already a bit overwhelmed with all the projects...

I think it would be cool to collaborate with the ProtoSchool work that @mikeal's team is doing too.

**Comment by mikeal** [comment]
Just to give you some quick insight in to some of the stuff the Community Team is putting together now and in Q1, we're trying to create two new entry points for people in the community that can be leveraged **across multiple projects** in the decentralization space.

One is ProtoSchool, which is a home for web based tutorials for people to learn how to use projects in the decentralization space.

Another is "The Publication" which we will be starting in Q1, which will be a blog or Medium publication. Basically, it's a home for demos and articles.

The goal here is to leverage a larger audience around decentralization across all of the projects rather than have every project resource be silo'd.

However, there's obviously resources that you'll still want to do on an individual project basis, like a website and github org, because it re-enforces a unique project identity and allows you to build your own community and contributor base.

For ProtoSchool, the biggest challenge with building a tutorial for a new project is just figuring out how to build the workflow for a testable code area that works for each project. We figured it out for some IPFS use cases but each project will take a little more work. What timeline do you think you'll be wanting to start on these? We can setup a call to discuss the project and kick around ideas for the best way to build the tutorials.

**Comment by jimpick** [comment]
Let's do a call!

I also want to discuss how to position everything so that people don't feel that the peer-* projects are in direct competition with other community projects, such as OrbitDB and Textile, and also other CRDT frameworks, and even non-IPFS decentralized web tech. There are a lot of good ideas out there.

Perhaps we should be providing some onramps and some content to help people decide which stacks they want to try building with?

**Comment by dirkmc** [comment]
I'm excited about ProtoSchool, I would have loved to have something like that when I first dived into IPFS-land. There's a _lot_ out there.

I think it's important to get the timing right - peer-star is still under pretty heavy development so I think we want to be careful not to encourage people to use it until we're sure the API won't have big changes.

**Comment by mikeal** [comment]
@dirkmc yes and no :) We found, in the process of building the initial materials and running a workshop, that the API for creating links in IPLD was just awful to use and to teach people. That ended up causing a lot of good changes in the API and the tutorials are much smoother now.

It's often the process of trying to present something to a broader audience that surfaces API issues you hadn't noticed because you'd sort of taken them for granted. I'd say, even if it's going to be a WIP for many months and not published until you shake some of these issues out, it might be worth trying to create a tutorial earlier rather than later.

**Comment by pgte** [comment]
@mikeal yes, let's talk! I set up an issue for this and a Doodle: https://github.com/ipfs/dynamic-data-and-capabilities/issues/53

**Comment by dirkmc** [comment]
@mikeal that's a good point. I look at peer-star-app totally differently when I'm building an app on top of it, as opposed to working on it directly

**Comment by pgte** [comment]
Continuing the community tutorials here: https://github.com/ipfs/dynamic-data-and-capabilities/issues/61
