### ISSUE TITLE
Managing Identity

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star#3]
Some questions regarding identity and how it is being implemented and exposed here:

- **What services and guarantees do you want to provide to apps built on top of this?**
- **What strategy / strategies do you plan on providing identity service(s)?**
- **What API do you plan on exposing?**

**Comment by pgte** [comment]
@fritzy ping

**Comment by fritzy** [comment]
> What services and guarantees do you want to provide to apps built on top of this?

Services: Registration, email confirmation, password resetting, session proof generation.

Guarantees: Attestation of the session and it's public key to the user of the identity service, and in turn, authorship of any operations added to the CRDT.

> What strategy / strategies do you plan on providing identity service(s)?

Using "webcrypto.subtle", the client will generate a key-pair for signing operations. The client will generate a DID, submit it with a signature to the identity service, and receive a proof in turn.

A client, when receiving an operation, will be given the DID id to look up the public key and proof. The chain of proofs looks like this.

operation is signed by key claiming DID id -> DID public key proves signature -> id service attestation of DID in the form of the proof provides proof of user@service.

> What API do you plan on exposing?

A server side rendered HTML interface for registration and login, a REST API for submitting DIDs and retrieving attestation with proofs.

uPort provides a similar service using ethereum, but a) It looks like they're using test rather than main Ethereum still b) They require an unclear app service that they have no documentation for in order to bootstrap the client into making API calls using the registered application secrets. c) Their DID attestation service is only used for the mobile client to use the API, and it's unclear if they have other use cases in mind. d) This will serve as a good example of a DID attestation service that other identity providers can provide in a more straightforward manner than relying on ethereum (like Keybase).

At some point in the near future, uPort might be viable despite those points.

**Comment by fritzy** [comment]
Once you have the proof, you will not have to look it up again, so operations can be created/verified even if you're offline. If you've never talked to a DID attestation identity service, then the application may accept you as a client session by your public key rather than by a centralized identity.

**Comment by fritzy** [comment]
For reference, this is the DID format: https://w3c-ccg.github.io/did-spec/

**Comment by fritzy** [comment]
Offline identities are simply the session-public key documented in a DID document, stored in a related session CRDT by the author.

**Comment by pgte** [comment]
@fritzy thank you, the path is much clearer to me now! Some questions:

## 1.
Upon receiving a new operation, a replica must validate that the signature matches the author DID. For that, he must retrieve the DID document, which contains the public key. Should this document be stored in a shared CRDT (with all the security pitfalls involved), or should we use a naming system to resolve that? (I'm thinking IPNS, for instance) I think the later, but I'm not 100% sure..

## 2.
After somehow retrieving the DID document containing the public key and validating the operation signature, a replica should then contact the attestation service to either a) retrieve the claimed identity or b) verify the identity claim somehow contained in the operation. 
The question is: how is the identity (user@service) linked to the session DID? Does the attestation service provide that resolution, or does the operation contain the user identity proof?

**Comment by fritzy** [comment]
1. @pgte We can use a DID id like id:ipfs:[address] and code that as the "user/session" in the CRDT. Remember that if an identity service is being used, they have to attest the DID as being user@service and provide a proof as well.

2. The DID itself contains a signature of the whole thing being signed by the private key associated with the public key contained within. The id service provides a proof of attestation that can be retrieved based on the "service" field in the DID.

If there's no id service involved, each peer must accept the signed DID at the client-specific value. If there is an id service listed in the DID, the peer can get the proof from the service that there is a user that may span multiple DID/keys.

**Comment by pgte** [comment]
@fritzy Thanks for the explanation, it's a bit clearer to me, but I'm not sure I fully understand:

1. You mean that the author will embed the DID id in the CRDT operation, right? But how does that replica get the public key for the DID id? Is it from the DID document? Where is that document stored?
2. What is the ID service interface? Who resolves the session DID id into the "real" identity and how?

**Comment by fritzy** [comment]
Yes, the author embeds the DID ID in each CRDT operation. The DID id resolves to an IPFS address with the DID, which contains the public key. The DID document is an IPFS file.

The other replicas can resolve the a broader identity if the DID contains "service" entry, which provides an endpoint for the proof. The proof is something signed by the id service showing attestation of the DID and service user. It's a few jumps, but the client needs to do it only once per user that it interacts with.

1. A peer client receives an signed operation.
2. The peer looks up the DID by the the DID id, which is an IPFS address.
3. The peer uses the public key in the DID to verify the signature of the operation.
4. The peer uses the "service" endpoint in the DID document to retrieve the attestation proof.
5. The peer validates the proof with the public key of the service. The attests that the DID belongs to the service user.

The service has attested it, because the user was logged into the service when it requested attestation of the DID, which was signed by the containing public key. So the service user is requesting that the DID be associated with user@service.

When subsequent operations are received, the peer needs to only validate the signature of the operation since the DID is cached and marked as valid. More than one DID may belong to a single service@user, as that user may have other clients and sessions.

**Comment by pgte** [comment]
@fritzy thank you for the explanation! Ok, so, if I understand this correctly, the identity service stores the relation between the session DID and the identity of the user (and is in a privileged and compromisable position).

What do you think about making the real identity ("I have e-mail address user@servive") be a verifiable claim, [issues by the issuer](https://www.w3.org/TR/verifiable-claims-use-cases/#issue-claim), [stored and transmitted by the holder](https://www.w3.org/TR/verifiable-claims-use-cases/#store-move-claim) and [verified by the peer](https://www.w3.org/TR/verifiable-claims-use-cases/#verify-claim)?

**Comment by jonnycrunch** [comment]
Yes, so... I've been working on [ipid](https://www.github.com/jonnycrunch/ipid) that is the DID method spec implemented on top of IPFS, specifically IPNS.  However, the current >60 sec resolve is much too long for interop with other methods.  At present, we are working with ED25519 and secp256k1 EC Diffie-hillman to do DID-Auth ( see:  [iiw 26](https://github.com/windley/IIW_homepage/raw/gh-pages/assets/proceedings/IIWXXVI_Book_of_Proceedings.pdf) ), which is done over libp2p.

**Comment by pgte** [comment]
@jonnycrunch that's super cool, thank you for sharing! I'm sure I'll have a few questions once I get a better understanding of how you implemented this.

I didn't know about [DID-Auth](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/master/draft-documents/did_auth_draft.md).

Thank you again!

**Comment by pgte** [comment]
All identity conversations should now be using https://github.com/ipfs-shipyard/pm-idm
