### ISSUE TITLE
CRDT API

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star#5]
Do you plan on providing an unified eventually consistent replicated data type? If so, what API are you considering on exposing?

**Comment by fritzy** [comment]
My plan is: collections of defined models -- so tables, basically. Patterns for usage, refs to other table rows, ACL, etc are all well-known.

**Comment by pgte** [comment]
@fritzy Some questions for you.

To implement a "table" would be use a register-like type?
I think this is ok, but the user should be aware that the entire table is going to be replicated locally...

If so, what about row-level conflicts? Do you intend to expose them (like in the multi-value register) or use an automatic conflict resolution strategy (like last-write-wins)?

Do you have a (draft) API documented somewhere?

**Comment by fritzy** [comment]
I do not have a draft document, but I was thinking it would be a subset of https://github.com/fritzy/dulcimer (the README has a robust API). Duclimer was meant to work with leveldb, and so would work with a register just fine (and indexdb). It could actually be many tables in one.

Row-level conflicts should only happen with the merging of a branch if we use instance-based vector clocks. I believe this was discussed in another issue. In any case, a conflict should be resolved at the application layer with a new operation. I know I had plans for this for Dulcimer (years ago) because it supports Riak.

In any case, maybe this is waaaaay over-blown of an API for such a type, but it would give application developers a lot of power by handling complexity of foreign relationships and such for them.

**Comment by pgte** [comment]
Peer-CRDT supports multi-value registers, which work with a vector clock underneath, perhaps take a look at that..

Also, it supports composition, so you could have a key where the value is another arbitrary CRDT (uses an independent causal tree).
